spring:
  application:
    name: gateway
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://keycloak:8080/realms/digital-money-house
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: userService
          uri: lb://userService
          predicates:
            - Path=/users/**
        - id: userService
          uri: lb://userService
          predicates:
            - Path=/cards/**
        - id: userService
          uri: lb://userService
          predicates:
            - Path=/accounts/**
        - id: registrationUserService
          uri: lb://registrationUserService
          predicates:
            - Path=/registration/**
server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
